### ISSUE TITLE
HHVM 3.9.1 compatibility

### ISSUE THREAD

**Issue by barbu110** [fredemmott/hhvm-autoload#6]
Hi!

Isn't this compatible with HHVM 3.9.1? I see the requirement is HHVM 3.11, but I not sure if that's reallt necessary. Is it?

**Comment by fredemmott** [comment]
So, I hadn't tested and assumed it wouldn't work because there's a load of bugfixes that look relevant for shapes in 3.10; that said, it passes the typechecker, and the test suite is all good. I'd rather not downgrade the requirement though until there's a real-world test - if you're able to do this, that'd be great.

**Comment by fredemmott** [comment]
3.9 is EOL: https://docs.hhvm.com/hhvm/installation/introduction#prebuilt-packages__lts-releases
